### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by javornikolov**
== Release 0.4.0

* Improvements
  * Use latest latest nokogiri version 1.6, thor 0.19.1 (#18)
  * Add support for latest rspec 3.x (#13)
  * Added --capture option to plsql-spec to indicate when to capture the output (#10)
  * Tested with Ruby version 2.2.0
  * Tested with ruby-oci8 version 2.1.7
* Buf fixes
  * fix for cli diff issue related to color rendering (#14)
* Internal (development) improvements
  * Ensure DATABASE\_PORT is Fixnum (#16)
  * Coverage test fix: compile plsql with optimize level 1 (#13)
  * Tests: allow fully-qualified service name connection (#12)
  * Migrate tests to rspec 3.x, using expect syntax (#13)
  * Use latest jeweler 2.0.1 (#18)

### CODE REVIEW

**Comment by javornikolov** [comment]
@rsim, I'm planning to release 0.4.0. Any concerns?

**Comment by jgebal** [comment]
@javornikolov Seems that Raimonds is now either very busy nowadays.
I hope everything is well and you will get a green light for a release.
@rsim If you don't have any objections, please confirm. It would be nice to have ruby-plsql-spec updated with newest library versions.

**Comment by rsim** [comment]
@javornikolov Sorry for not responding earlier.
It's OK to release the new version.

**Comment by javornikolov** [comment]
Thanks! I'll release shortly.

**Pull request merged**
