### PR TITLE
Fixed coverage support for PACKAGE Body so that lines covered in PACK…

### PR DESCRIPTION
**Pull request by vonahnen**
…AGE headers aren't counted towards it.

### CODE REVIEW

**Comment by vonahnen** [comment]
Not sure who maintains the build scripts for this repo, but the script .travis/oracle/install.sh is failing...

**Comment by javornikolov** [comment]
Thank you @vonahnen for this pull request! Would it be feasible to add some tests for that change?

**Comment by javornikolov** [comment]
> Not sure who maintains the build scripts for this repo, but the script .travis/oracle/install.sh is failing...
> 
> unzip: cannot find zipfile directory in one of oracle-xe-11.2.0-1.0.x86_64.rpm.zip or
> oracle-xe-11.2.0-1.0.x86_64.rpm.zip.zip, and cannot find oracle-xe-11.2.0-1.0.x86_64.rpm.zip.ZIP, period.

I'll have a look at that. We had a similar issue with `ruby-plsql`. I'll double check if the solution which we used there is still working and apply it here soon.

**Comment by vonahnen** [comment]
Awesome, and yes I can write some tests. I'll update once I get a chance to write those.

**Comment by javornikolov** [comment]
I managed to fix the Travis CI (the related PR #44 is already merged into master).

**Comment by vonahnen** [comment]
@javornikolov - tests updated.

**Comment by javornikolov** [comment]
Thank you @vonahnen! It looks good to me. Merging...

**Pull request merged**
