### PR TITLE
Add support for rspec 3.x

### LINKED ISSUE #15: Update to be compatible with latest ruby-plsql and rspec
I cannot use ruby-plsql-spec with rspec 3x as the dependencies indicate compatibility with rspec 2x:
gem 'rspec', '~> 2.0'
...
      s.add_runtime_dependency(%q<rspec>, ["~> 2.0"])

The ruby-plsql however has dependencies updated.

### PR DESCRIPTION
**Pull request by javornikolov**
This is aiming to resolve #15

Add support for rspec 3.x (development and runtime)

### CODE REVIEW

**Comment by jgebal** [comment]
Do you need some support on review of that change?
When you will be able to merge it to master and bump the new version?

**Comment by javornikolov** [comment]
I'm merging it :-) Would be great if you can provide some feedback whether it works in your environment. If it's all OK, we can perhaps bump up the version and issue new release.

**Comment by jgebal** [comment]
I will check it on my local project, thanks Yavor.

**Comment by jgebal** [comment]
I would be happy to contribute, but i'm an Oracle Developer and i'm only learning ruby to the extent needed for testing (so fat).
I have some issues running the ruby-plsql-spec project on my local machine.
Some gems are getting messy (i'm using rubymine 7.0.2)

**Comment by jgebal** [comment]
I have tested the new gem functionality.
Init new project
plsql-spec init -> OK

Run on existing projects:
plsql-spec run -> OK
plsql-spec run --html -> OK
plsql-spec run --coverage -> OK

**Pull request merged**
